### ISSUE TITLE
1 layer of a unit cell (Z voxels = 1)

### ISSUE THREAD

**Issue by tomfishh** [fequalsf/Crystallon#5]
Fantastic software! I don't seem to be able to voxelize (Morph Between Surfaces) with only one voxel in the Z direction. Is there any way to achieve this? Thanks

**Comment by fequalsf** [comment]
Yes sorry this is a known bug I haven't got around to fixing and updating... 

What I usually do is use the "divide surface" component in Crystallon to create meshes to work with. Then use the "morph between meshes" component.

This is actually the route I will take completely in the next version, so this will all be one component to replace "morph between surfaces".

I've attached a file here for you. Hope this helps for now.

Cheers!

![image](https://user-images.githubusercontent.com/5560725/170199303-c9cf0f63-bf94-40b7-a77d-edc57a354315.png)

[morph-between-meshes.zip](https://github.com/fequalsf/Crystallon/files/8768651/morph-between-meshes.zip)

**Comment by tomfishh** [comment]
Perfect, I think that could really help me. Thanks so much for this!

**Comment by fequalsf** [comment]
Cheers! Promise it will be fixed in the next update!
